config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  
  resources :users, only: [:new, :show, :create] do
    member do
      get :followings
      get :followers
      get :favorites
    end
  end
  
  resources :recipes do
    resources :ingredients, shallow: true
    resources :instractions, shallow: true
  end
  
  resources :relationships, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :recipe
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  validates :name, presence: true, length: { maximum: 50 }
  validates :amount, length: { maximum: 50 }
  
  belongs_to :recipe
end

app/models/instraction.rb
class Instraction < ApplicationRecord
  validates :content, length: { maximum: 255 }
  
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  validates :title, presence: true, length: { maximum: 50 }
  validates :content, length: { maximum: 255 }
  validates :volume, presence: true, numericality: { only_integer: true, less_than: 50 }
  
  belongs_to :user
  has_many :ingredients, dependent: :destroy
  has_many :instractions, dependent: :destroy
  accepts_nested_attributes_for :ingredients, allow_destroy: true
  accepts_nested_attributes_for :instractions, allow_destroy: true
  mount_uploader :picture, PictureUploader
  
  private
  
  def picture_size
    if picture.size > 20.megabytes
      errors.add(:picture, "should be less than 20MB")
    end
  end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :follow, class_name: 'User'
  
  validates :user_id, presence: true
  validates :follow_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  
  has_many :recipes, class_name: 'Recipe'
  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverses_of_relationship, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverses_of_relationship, source: :user
  has_many :favorites, dependent: :destroy
  has_many :favorite_recipes, through: :favorites, source: :recipe
  
  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end
  
  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end
  
  def following?(other_user)
    self.followings.include?(other_user)
  end
  
  def favorite(recipe)
    self.favorites.find_or_create_by(recipe_id: recipe.id)
  end
  
  def unfavorite(recipe)
    favorite = self.favorites.find_by(recipe_id: recipe.id)
    favorite.destroy if favorite
  end
  
  def favorite?(recipe)
    self.favorite_recipes.include?(recipe)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  include SessionsHelper
  
  private
  
  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
  
  def counts(user)
    @count_user_recipes = user.recipes.count
    @count_followings = user.followings.count
    @count_followers = user.followers.count
    @count_favorites = user.favorite_recipes.count
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  
  def create
    recipe = Recipe.find(params[:recipe_id])
    current_user.favorite(recipe)
    flash[:success] = 'お気に入りに登録しました。'
    redirect_back(fallback_location: root_path)
  end
  
  def destroy
    recipe = Recipe.find(params[:recipe_id])
    current_user.unfavorite(recipe)
    flash[:success] = 'お気に入りを解除しました。'
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show]
  before_action :correct_user, only: [:destroy, :edit, :update]
  before_action :require_user_logged_in, only: [:new, :create, :edit, :update, :destroy]
  
  def show
  end
 
  def new
    @recipe = current_user.recipes.build
    @recipe.ingredients.build
    @recipe.instractions.build
  end

  def create
    @recipe = current_user.recipes.build(recipe_params)
    if @recipe.save
      flash[:success] = 'レシピを投稿しました。'
      redirect_to current_user
    else
      flash[:danger] = 'レシピの投稿に失敗しました。'
      render :new
    end
  end

  def edit
  end

  def update
    if @recipe.update(recipe_params)
      flash[:success] = 'レシピを更新しました。'
      redirect_to @recipe
    else
      flash.now[:danger] = 'レシピを更新できませんでした。'
      render :edit
    end
  end

  def destroy
    @recipe.destroy
    flash[:success] = 'レシピを削除しました。'
    redirect_to root_path
  end
  
  private
  
  def recipe_params
    params.require(:recipe).permit(
      :title, :content, :volume, :picture,
      ingredients_attributes: [:id, :name, :amount, :_destroy], 
      instractions_attributes: [:id, :content, :_destroy]
      )
  end
  
  def set_recipe
    @recipe = Recipe.find_by(id: params[:id])
  end
  
  def correct_user
    @recipe = current_user.recipes.find_by(id: params[:id])
    unless @recipe
      redirect_to root_path
    end
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :require_user_logged_in
  
  def create
    user = User.find(params[:follow_id])
    current_user.follow(user)
    flash[:success] = 'フォローしました。'
    redirect_to user
  end

  def destroy
    user = User.find(params[:follow_id])
    current_user.unfollow(user)
    flash[:success] = 'フォローを解除しました。'
    redirect_to user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインしました。'
      redirect_to root_path
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_path
  end
  
  private
  
  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      session[:user_id] = @user.id
      return true
    else
      return false
    end
  end
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
    @recipes = Recipe.all.order('created_at DESC').page(params[:page])
  end
  
  def favorite?(recipe)
    user.favorite_recipes.include?(recipe)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:show, :followings, :followers]
  before_action :set_user, only: [:show, :followings, :followers, :favorites]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = 'ユーザー登録しました。'
      session[:user_id] = @user.id
      redirect_to @user
    else
      flash.now[:danger] = 'ユーザーの登録に失敗しました。'
      render :new
    end
  end
  
  def show
    @recipes = @user.recipes.order('created_at DESC').page(params[:page])
    counts(@user)
  end
  
  def followings
    @followings = @user.followings.page(params[:page])
    counts(@user)
  end
  
  def followers
    @followers = @user.followers.page(params[:page])
    counts(@user)
  end
  
  def favorites
    @favorites = @user.favorite_recipes.page(params[:page])
    counts(@user)
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
  
  def set_user
    @user = User.find_by(id: params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    !!current_user
  end
end

app/views/favorites/_favorite_button.html.erb
<% if current_user.favorite?(recipe) %>
  <%= form_for(current_user.favorites.find_by(recipe_id: recipe.id), html: { method: :delete }) do |f| %>
    <%= hidden_field_tag :recipe_id, recipe.id %>
    <%= f.submit 'お気に入り中', class: 'btn btn-unfavorite btn-block btn-sm' %>
  <% end %>
<% else %>
  <%= form_for(current_user.favorites.build) do |f| %>
    <%= hidden_field_tag :recipe_id, recipe.id %>
    <%= f.submit 'レシピをお気に入り', class: 'btn btn-favorite btn-block btn-sm' %>
  <% end %>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <p class="text-muted text-center">&copy; 2017 RECIPEBOX.</p>
</footer>

app/views/layouts/_navbar.html.erb
<header>
  <nav class="navbar navbar-default navbar-static-top">
    <div class="container">
      <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-left" href="/"><img src="/images/logo-img.png" alt="RecipeBox"></a><a class="navbar-brand" href="/">RecipeBox</a>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <% if logged_in? %>
            <li data-turbolinks="false">
              <%= link_to new_recipe_path do %>
                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                レシピを書く
              <% end %>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                <span class="glyphicon glyphicon-user"></span><%= current_user.name %><span class="caret"></span>
              </a>
              <ul class="dropdown-menu" role="menu">
                <li><%= link_to 'マイページ', user_path(current_user) %></li>
                <li role="separator" class="divider"></li>
                <li><%= link_to 'ログアウト', logout_path, method: :delete %></li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to 'ユーザー登録', signup_path %></li>
            <li><%= link_to 'ログイン', login_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <title>RecipeBox</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/earlyaccess/kokoro.css" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/earlyaccess/sawarabigothic.css" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Walter+Turncoat" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Josefin+Slab" rel="stylesheet">
    <link href="https://fonts.googleapis.com/earlyaccess/nikukyu.css" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <script type="text/javascript" src="js/bootstrap-filestyle.min.js"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <%= yield :cover %>

    <div class="container">
      <%= render 'layouts/flash_messages' %>

      <%= yield %>
    </div>
  </body>
  <%= render 'layouts/footer' %>
</html>

app/views/recipes/_form.html.erb
<div class="col-xs-12">
  <div class="form-horizontal well-color well well-lg row">
    <%= form_for(recipe, html: { multipart: true }) do |f| %>
      <div class="form-group well well-lg row">
        <div class="form-group col-xs-12">
          <%= f.label :name, 'レシピタイトル' %>
          <%= f.text_area :title, class: 'form-control', placeholder:'レシピタイトルを入力' %>
        </div>
        <div class="form-group col-xs-12">
          <%= f.label :name, 'このレシピについて' %>
          <%= f.text_area :content, class: 'form-control', placeholder: 'レシピコメント（おすすめポイントなど）' %>
        </div>
        <div class="form-group col-xs-12">
          <%= f.label :name, '分量（〜人分）' %>
          <%= f.number_field :volume, class: 'form-control', placeholder: '〜人分、整数で入力(例：3)' %>
        </div>
        <div data-turbolinks="false", class="form-group col-xs-12">
          <%= f.label :name, 'レシピフォト' %>
          <%= f.file_field :picture, class: 'filestyle', "data-buttonText":"Choose file", "data-input":"false", accept:'image/jpeg,image/jpg,image/gif,image/png' %>
        </div>
      </div>
      <div class="form-group well well-lg row">
        <%= f.label :name, '材料を入力' %>
        <table class="table table-striped table-hover">
          <tbody>
            <tr>
              <th>材料名</th>
              <th>分量</th>
            </tr>
            <%= f.nested_fields_for :ingredients, wrapper_tag: :tr do |q| %>
              <%= q.hidden_field :id %>
              <td class="col-xs-6"><%= q.text_field :name, class: 'form-control', placeholder:'材料名' %></td>
              <td class="col-xs-6"><%= q.text_field :amount, class: 'form-control', placeholder:'分量（例：30g, 大さじ1）' %></td>
              <td><%= q.remove_nested_fields_link 'x', class: 'form-control close', role: 'button' %></td>
            <% end %>
          </tbody>
        </table>
            <%= f.add_nested_fields_link :ingredients, '材料名をさらに追加', class: 'btn btn-warning', role: 'button' %>
      </div>
      <div class="form-group well well-lg row">
        <%= f.label :name, '作り方を入力' %>
        <table class="table table-striped table-hover">
          <tbody>
            <tr>
              <th>作り方</th>
            </tr>
            <%= f.nested_fields_for :instractions, wrapper_tag: :tr, class: 'row' do |q| %>
              <%= q.hidden_field :id %>
              <td class="col-xs-12"><%= q.text_field :content, class: 'form-control', placeholder:'作り方（手順に応じて入力フィールドを追加してください）' %></td>
              <td><button type="button" class="close form-control"><span aria-hidden="true"><%= q.remove_nested_fields_link %></span></button></td>
            <% end %>
          </tbody>
        </table>
            <%= f.add_nested_fields_link :instractions, '作り方をさらに追加', class: 'btn btn-warning', role: 'button' %>
      </div>
      <div class="row">
        <%= f.submit 'レシピを投稿する', class: 'btn btn-success btn-block' %>
      </div>
    <% end %>
  </div>
</div> 

<script type="text/javascript">
  $('#recipe_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 20) {
      alert('Maximum file size is 20MB. Please choose a smaller file.');
    }
  });
</script>

app/views/recipes/_recipes_short.html.erb
<% recipes.each do |recipe| %>
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail image-responsive", style="overflow: hidden;">
      <% unless recipe.picture? %>
        <div style="height: 250px; display:table; margin: 10px auto 5px;"><%= image_tag "/images/sample00.jpg", width: '250px', height: '250px' %></div>
      <% else %>
        <div style="height: 250px; display:table; margin: 10px auto 5px;"><%= image_tag recipe.picture.url, width: '250px', height: '250px' %></div>
      <% end %>
      <div class="caption", style="overflow:hidden; height: 180px;">
        <div style="height: 37px; overflow:hidden;"><h3 class="text-warning recipe-title", style="font-size: 17.7px; line-height: 1.45; margin-top: 10px;"><%= recipe.title %></h3></div>
        <% user = recipe.user %>
        <div class="bg-danger", style="margin: 6px auto 6px;">
          <%= link_to user.name, user_path(user), class: 'btn btn-xs btn-name text-left' %><span class="btn btn-xs text-muted pull-right"><%= l recipe.created_at, format: :short %></span>
        </div>
        <div>
          <p class="text-muted", style="height: 45px; overflow:hidden; line-height: 1.3; font-size: 13px; text-align: justify;"><%= recipe.content %></p>
        </div>
        <div>
          <%= link_to 'レシピ詳細', recipe_path(recipe), class: "btn btn-sm btn-block btn-show" %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<div class="container">
  <div class="jumbotron well-color text-center">
    <h2 style="line-height: -.08em; letter-spacing: .1em;">Edit Recipe Note</h2>
  </div>
  <%= render 'form', recipe: @recipe %>
</div>

app/views/recipes/new.html.erb
<div class="container">
  <div class="jumbotron well-color text-center">
    <h2 style="line-height: -.08em; letter-spacing: .1em;">Write Recipe Note</h2>
  </div>
  <%= render 'form', recipe: @recipe %>
</div>

app/views/recipes/show.html.erb
<div class="container">
  <div class="well well-lg col-lg-offset-1 col-lg-10">
    <h1 class="page-header recipe-title text-center"><%= @recipe.title %></h1>
    <div class="panel-default">
      <div class="panel-heading">
        <h2 class="panel-title">
          <% user = @recipe.user %>
          <span class="glyphicon glyphicon-user"></span><%= link_to user.name, user_path(user), class: 'text-left btn btn-xs btn-name' %><span class="text-muted pull-right"><%= l @recipe.created_at, format: :short %></span>
        </h2>
      </div>
      <div class="panel-body">
        <p><%= @recipe.content %></p>
      </div>
      <div class="img-thumbnail", style="display: block; margin: 0 auto 10px; background: #fff; height: 260px; width: 260px; box-shadow: 0px 0px 5px rgba(0,0,0,0.2);">
        <% unless @recipe.picture? %>
          <div style="height: 250px; display:table; margin: 0px auto 5px;"><%= image_tag "/images/sample00.jpg", width: '250px', height: '250px' %></div>
        <% else %>
          <div style="height: 250px; display:table; margin: 0px auto 5px;"><%= image_tag @recipe.picture.url, width: '250px', height: '250px' %></div>
        <% end %>
      </div>
      <div class="table-responsive">
        <table class="table table-striped table-condensed">
          <thead>
            <tr><th>材料</th><th>（<%= @recipe.volume %>人分）</th></tr>
          </thead>
          <% @recipe.ingredients.each do |ingredient| %>
            <tbody>
              <tr><td><%= ingredient.name %></td><td><%= ingredient.amount %></td></tr>
            </tbody>
          <% end %>
        </table>
      </div>
      <div class="panel-body">
        <h3 class="text-center h3-instractions">作り方</h3>
        <div class="col-xs-offset-1 col-xs-10 col-sm-offset-2 col-sm-8 col-md-offset-4 col-md-8">
          <% @recipe.instractions.each_with_index do |instraction, index| %>
            <p><%= index+1 %>.<%= instraction.content %></p>
          <% end %>
        </div>
      </div>
      <div class="panel-body">
        <% if @recipe.user = current_user %>
          <%= link_to 'レシピを編集する', edit_recipe_path(@recipe), class: "btn btn-sm btn-info btn-block" %>
          <%= link_to 'このレシピを削除', @recipe, method: :delete, data: { confirm: '本当に削除してよろしいですか？' }, class: "btn btn-sm btn-default btn-block" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/relationships/_follow_button.html.erb
<% unless current_user == user %>
  <% if current_user.following?(user) %>
    <%= form_for(current_user.relationships.find_by(follow_id: user.id), html: { method: :delete }) do |f| %>
      <%= hidden_field_tag :follow_id, user.id %>
      <%= f.submit 'フォロー中', class: 'btn btn-xs btn-unfollow' %>
    <% end %>
  <% else %>
    <%= form_for(current_user.relationships.build) do |f| %>
      <%= hidden_field_tag :follow_id, user.id %>
      <%= f.submit 'フォロー', class: 'btn btn-xs btn-follow' %>
    <% end %>
  <% end %>
<% end %>

app/views/toppages/index.html.erb
<% content_for :cover do %>
  <div class="cover">
    <div class="cover-inner">
      <div class="cover-contents">
        <h1>レシピボックス</h1>
        <p>”あの味”、残しませんか？</p>
        <h2>もっと気軽にレシピ保存を。</h2>
        <% if logged_in? %>
          <%= link_to 'レシピを書く', new_recipe_path, class:"btn btn-new-recipe btn-md" %>
          <%= link_to 'マイページへ', user_path(current_user), class:"btn btn-mypage btn-md" %>
        <% else %>
          <%= link_to '新規登録', signup_path, class:"btn btn-new btn-md" %>
          <%= link_to 'ログイン', login_path, class: "btn btn-login btn-md" %>
        <% end %>
      </div>
    </div>
  </div>
<% end %>
<%= render 'recipes/recipes_short', recipes: @recipes %>

app/views/users/_users.html.erb
<% users.each do |user| %>
  <div class="well-users">
    <ul class="users-ul">
      <li>
        <span class="pull-left">
          <%= link_to user.name, user_path(user), class: 'users-name' %>
        </span>
        <span class="follow-button">
          <%= render 'relationships/follow_button', user: user %>
        </span>
      </li>
      <li>
        <span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span>
        <%= link_to user_path(user) do %>投稿レシピ数<span class="badge badge-color"><%= @count_user_recipes %></span><% end %>
      </li>
      <li>
        <span class="glyphicon glyphicon-heart" aria-hidden="true"></span>
        <%= link_to followings_user_path(user) do %>フォロー<span class="badge badge-color"><%= @count_followings %></span><% end %>
      </li>
      <li>
        <span class="glyphicon glyphicon-heart-empty" aria-hidden="true"></span>
        <%= link_to followings_user_path(user) do %>フォロワー<span class="badge badge-color"><%= @count_followers %></span><% end %>
      </li>
    </ul>
  </div>
<% end %>
<%= paginate users %>

app/views/users/favorites.html.erb
<div class="user-profile">
  <div class="user-show-panel">
    <div class="name user-name text-center">
      <h1><%= @user.name %></h1>
    </div>
    <div class="follow-button text-center">
      <%= render 'relationships/follow_button', user: @user %>
    </div>
    <div class="user-count">
      <div class="follow-users">
        <span class="glyphicon glyphicon-star" aria-hidden="true"></span>お気に入りレシピ<span class="badge badge-color"><%= @count_favorites %></span>
      </div>
    </div>
  </div>
  <div class="user-show-body">
    <%= render 'recipes/recipes_short', recipes: @favorites %>
    <%= paginate @favorites %>
  </div>
</div>

app/views/users/followers.html.erb
<div class="followings">
  <div class="name users-show-name text-center">
      <h1><%= @user.name %></h1>
  </div>
  <div class="follow-users">
    <span class="glyphicon glyphicon-heart" aria-hidden="true"></span>
    フォロワー<span class="badge badge-color"><%= @count_followers %></span>
  </div>
  <%= render 'users', users: @followers %>
</div>

app/views/users/followings.html.erb
<div class="followings">
  <div class="name users-show-name text-center">
      <h1><%= @user.name %></h1>
  </div>
  <div class="follow-users">
    <span class="glyphicon glyphicon-heart" aria-hidden="true"></span>
    フォロー<span class="badge badge-color"><%= @count_followings %></span>
  </div>
  <%= render 'users', users: @followings %>
</div>

app/views/users/new.html.erb
<div class="row create-user">
  <div class="col-xs-offset-1 col-xs-10">
    <div class="panel panel-default">
      <div class="panel-heading">ユーザー登録</div>
      <div class="panel-body">
        <%= form_for(@user) do |f| %>
          <div class="form-group">
            <%= f.label :name, 'お名前' %>
            <%= f.text_field :name, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :email, 'メールアドレス' %>
            <%= f.email_field :email, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :password, 'パスワード' %>
            <%= f.password_field :password, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :password_confirmation, 'パスワード（確認）' %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>
          </div>

          <div class="text-right">
            <%= f.submit '登録', class: 'btn btn-success btn-block' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="user-profile">
  <div class="user-show-panel">
    <div class="name user-name text-center">
      <h1><%= @user.name %></h1>
    </div>
    <div class="follow-button text-center">
      <%= render 'relationships/follow_button', user: @user %>
    </div>
    <div class="user-count">
      <ul>
        <li>
          <span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span>
          投稿レシピ数
          <span class="badge badge-color"><%= @count_user_recipes %></span>
        </li>
        <li>
          <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
          <%= link_to favorites_user_path(@user) do %>お気に入りレシピ<span class="badge badge-color"><%= @count_favorites %></span><% end %>
        </li>
        <li>
          <span class="glyphicon glyphicon-heart" aria-hidden="true"></span>
          <%= link_to followings_user_path(@user) do %>フォロー<span class="badge badge-color"><%= @count_followings %></span><% end %>
        </li>
        <li>
          <span class="glyphicon glyphicon-heart-empty" aria-hidden="true"></span>
          <%= link_to followers_user_path(@user) do %>フォロワー<span class="badge badge-color"><%= @count_followers %></span><% end %>
        </li>
      </ul>
    </div>
  </div>
  <div class="user-show-body">
    <%= render 'recipes/recipes_short', recipes: @recipes %>
    <%= paginate @recipes %>
  </div>
</div>